<?php
$sql = "CREATE USER \'bredor\'@\'localhost\' IDENTIFIED VIA mysql_native_password USING \'***\';GRANT ALL PRIVILEGES ON *.* TO \'bredor\'@\'localhost\' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `bredor`;GRANT ALL PRIVILEGES ON `bredor`.* TO \'bredor\'@\'localhost\';";
?>